import { defineField, defineType } from "sanity";

const money = (name: string, title: string) => defineField({ name, title, type: "number", readOnly: true });

export const salesQuote = defineType({
  name: "salesQuote",
  title: "Sales quotes",
  type: "document",
  fields: [
    defineField({ name: "portalEnvironment", title: "Portal environment", type: "string", readOnly: true, hidden: true }),
    defineField({ name: "quoteNumber", title: "Quote number", type: "number", readOnly: true }),
    defineField({ name: "quoteReference", title: "Quote reference", type: "string", readOnly: true }),
    defineField({ name: "documentType", title: "Document type", type: "string", readOnly: true, options: { list: [{ title: "Quote", value: "quote" }, { title: "Sales Order", value: "sales-order" }] } }),
    defineField({ name: "orderOf", title: "Source quote", type: "reference", to: [{ type: "salesQuote" }], readOnly: true }),
    defineField({ name: "baseQuoteNumber", title: "Original quote number", type: "number", readOnly: true }),
    defineField({ name: "revisionNumber", title: "Revision number", type: "number", readOnly: true }),
    defineField({ name: "status", title: "Status", type: "string", options: { list: [{title:"Customer Quoted",value:"customer-quoted"},{title:"Negotiating",value:"negotiating"},{title:"Awaiting Order",value:"awaiting-order"},{title:"Closed Won",value:"closed-won"},{title:"Closed Lost",value:"closed-lost"}] } }),
    defineField({ name: "previousRevision", title: "Previous version", type: "reference", to: [{ type: "salesQuote" }], readOnly: true }),
    defineField({ name: "supersededBy", title: "Superseded by", type: "reference", to: [{ type: "salesQuote" }], readOnly: true }),
    defineField({ name: "statusUpdatedAt", title: "Status last updated", type: "datetime", readOnly: true }),
    defineField({ name: "statusUpdatedBy", title: "Status updated by", type: "string", readOnly: true }),
    defineField({ name: "createdAt", title: "Created", type: "datetime", readOnly: true }),
    defineField({ name: "createdByName", title: "Salesperson", type: "string", readOnly: true }),
    defineField({ name: "createdByEmail", title: "Salesperson email", type: "string", readOnly: true }),
    defineField({ name: "quoteDate", title: "Quote date", type: "date", readOnly: true }),
    defineField({ name: "validUntil", title: "Valid until", type: "date", readOnly: true }),
    defineField({ name: "customerCompany", title: "Customer company", type: "string", readOnly: true }),
    defineField({ name: "customerContact", title: "Customer contact", type: "string", readOnly: true }),
    defineField({ name: "customerEmail", title: "Customer email", type: "string", readOnly: true }),
    defineField({ name: "customerTelephone", title: "Customer telephone", type: "string", readOnly: true }),
    defineField({ name: "address1", title: "Address line 1", type: "string", readOnly: true }),
    defineField({ name: "address2", title: "Address line 2", type: "string", readOnly: true }),
    defineField({ name: "town", title: "Town", type: "string", readOnly: true }),
    defineField({ name: "postcode", title: "Postcode", type: "string", readOnly: true }),
    defineField({ name: "quantity", title: "Quantity", type: "number", readOnly: true }),
    defineField({ name: "vehicleMake", title: "Make", type: "string", readOnly: true }),
    defineField({ name: "vehicleModel", title: "Model", type: "string", readOnly: true }),
    defineField({ name: "vehicleVariant", title: "Variant", type: "string", readOnly: true }),
    defineField({ name: "modelYear", title: "Model year", type: "string", readOnly: true }),
    defineField({ name: "transmission", title: "Transmission", type: "string", readOnly: true }),
    defineField({ name: "bodyType", title: "Body type", type: "string", readOnly: true }),
    money("co2", "CO₂"), money("p11d", "P11D"),
    defineField({ name: "colour", title: "Colour", type: "string", readOnly: true }),
    defineField({ name: "factoryOptions", title: "Factory options", type: "array", readOnly: true, of: [{ type: "object", fields: [defineField({ name: "description", type: "string" }), money("price", "Price")] }] }),
    defineField({ name: "dealerOptions", title: "Dealer fit options", type: "array", readOnly: true, of: [{ type: "object", fields: [defineField({ name: "description", type: "string" }), money("costPrice", "Cost price"), money("price", "Price")] }] }),
    money("basicListPrice", "Basic list price"), money("dealerDiscountPct", "Dealer discount %"), money("dealerMarginPct", "Dealer margin %"), money("dealerMarginOverride", "Dealer Discount manual"), money("dealerDiscountRetained", "Dealer discount retained"), money("commission", "Commission"), money("commissionPct", "Commission %"), money("manufacturerTerms", "Manufacturer terms"), money("evGrant", "EV Grant"), money("delivery", "PDI & Delivery"), money("onwardDelivery", "Onward Delivery"), money("vatPct", "VAT %"), money("rfl", "RFL"), money("firstRegistrationFee", "First registration fee"), money("totalDiscount", "Total discount"), money("totalBeforeVat", "Total before VAT"), money("vat", "VAT"), money("totalDue", "Total due"), money("orderTotal", "Order total"),
    money("priceOverride", "Manual price override"),
    defineField({ name: "commissionMode", title: "Commission mode", type: "string", readOnly: true }),
    defineField({ name: "internalNotes", title: "Internal notes", type: "text", readOnly: true }),
    defineField({ name: "calculationVersion", title: "Calculation version", type: "string", readOnly: true }),
    defineField({ name: "hubspotStatus", title: "HubSpot status", type: "string", readOnly: true }),
    defineField({ name: "hubspotError", title: "HubSpot error", type: "string", readOnly: true }),
    defineField({ name: "hubspotUpdatedAt", title: "HubSpot updated at", type: "datetime", readOnly: true }),
    defineField({ name: "hubspotUpdatedBy", title: "HubSpot updated by", type: "string", readOnly: true }),
    defineField({ name: "sharepointStatus", title: "SharePoint status", type: "string", readOnly: true }),
    defineField({ name: "sharepointSavedAt", title: "SharePoint saved at", type: "datetime", readOnly: true }),
    defineField({ name: "sharepointSavedBy", title: "SharePoint saved by", type: "string", readOnly: true }),
  ],
  preview: {
    select: { reference: "quoteReference", number: "quoteNumber", company: "customerCompany", total: "totalDue", status: "status" },
    prepare: ({ reference, number, company, total, status }) => ({ title: `Quote ${reference || number || "pending"}: ${company || "No customer"}`, subtitle: `${status || "issued"} | ${typeof total === "number" ? `£${total.toLocaleString("en-GB", { minimumFractionDigits: 2 })}` : ""}` }),
  },
});

